services:
  - type: web
    name: puppeteer-api
    env: node
    plan: starter
    buildCommand: |
      echo 'ğŸ‘· Installing puppeteer...'
      npm install
      echo 'ğŸ§ Installing Chromium...'
      npx puppeteer browsers install chrome --path=/opt/render/.cache/puppeteer
      echo 'âœ… Chromium install complete!'
    startCommand: node index.js
